"""
Regime Predictor — loads trained models and runs live inference for any ticker.

Runs the regime classifier, return regressor, and volatility regressor against
today's live feature row. Models must have been trained first (via the ML Admin
page or `python -m scripts.train_regime_classifier` etc.).

Stand-alone usage:
    python -m scripts.regime_predictor            # predict all WATCHLIST tickers
    python -m scripts.regime_predictor AAPL MSFT  # predict specific tickers

Constraints:
  - Read-only: never modifies candidate_provider.py / decision_provider.py
  - Gracefully returns warnings for models not yet trained
  - E*TRADE auth failures never halt predictions
"""
from __future__ import annotations

import sys
import json
import math
import warnings as _warnings
from pathlib import Path

# Suppress sklearn "X does not have valid feature names" noise — our feature
# matrix is a DataFrame built to match training columns; the warning is benign.
_warnings.filterwarnings(
    "ignore",
    message="X does not have valid feature names",
    category=UserWarning,
)

import joblib
import numpy as np
import pandas as pd


def _load_ml_config() -> dict:
    """Read [ml] section from config/secrets.toml with safe defaults."""
    try:
        try:
            import tomllib
        except ImportError:
            import tomli as tomllib
        _path = Path(__file__).resolve().parent.parent / "config" / "secrets.toml"
        cfg = tomllib.loads(_path.read_text(encoding="utf-8"))
        ml = cfg.get("ml", {})
        return {
            "return_regressor_enabled":      bool(ml.get("return_regressor_enabled", False)),
            "return_regressor_r2_threshold": float(ml.get("return_regressor_r2_threshold", 0.10)),
        }
    except Exception:
        return {"return_regressor_enabled": False, "return_regressor_r2_threshold": 0.10}

_ROOT = Path(__file__).resolve().parent.parent
_MODELS_DIR = _ROOT / "data" / "models"

_CLASSIFIER_PATH         = _MODELS_DIR / "regime_classifier.joblib"
_REGIME_CATBOOST_PATH    = _MODELS_DIR / "regime_catboost.joblib"
_RETURN_PATH             = _MODELS_DIR / "return_regressor.joblib"
_RETURN_CATBOOST_PATH    = _MODELS_DIR / "return_catboost.joblib"
_VOLATILITY_PATH     = _MODELS_DIR / "volatility_regressor.joblib"
_DIRECTION_PATH      = _MODELS_DIR / "direction_classifier.joblib"
_IV_DIRECTION_PATH   = _MODELS_DIR / "iv_direction_classifier.joblib"
_META_PATH           = _MODELS_DIR / "meta_ensemble.joblib"
_ANOMALY_PATH        = _MODELS_DIR / "anomaly_detector.joblib"

# Calibrated variants — preferred over raw models when they exist.
# Generated by scripts/calibrate_models.py (also auto-generated by each train_*.py).
_CLASSIFIER_CAL_PATH         = _MODELS_DIR / "regime_classifier_calibrated.joblib"
_REGIME_CATBOOST_CAL_PATH    = _MODELS_DIR / "regime_catboost_calibrated.joblib"
_DIRECTION_CAL_PATH     = _MODELS_DIR / "direction_classifier_calibrated.joblib"
_IV_DIRECTION_CAL_PATH  = _MODELS_DIR / "iv_direction_classifier_calibrated.joblib"
_META_CAL_PATH          = _MODELS_DIR / "meta_ensemble_calibrated.joblib"
_POP_CAL_PATH           = _MODELS_DIR / "pop_classifier_calibrated.joblib"

_CATEGORICAL_COLS = ("macd_trend", "trend", "spy_trend", "qqq_trend", "iwm_trend", "sector_etf", "sector_trend")
_POP_PATH        = _MODELS_DIR / "pop_classifier.joblib"

# Canonical label strings — must match label_encoder.classes_ from training.
_LABEL_UPTREND    = "Uptrend"
_LABEL_DOWNTREND  = "Downtrend"
_LABEL_RANGEBOUND = "Range-bound"
_LABEL_IV_EXP     = "Expanding"
_LABEL_IV_CON     = "Contracting"

# In-process model cache keyed by Path → (mtime, artifact).
# Safe with gunicorn workers=1 (current deployment).
# If workers > 1 each worker loads its own copy (~200MB × N workers).
# To scale: pin to workers=1 and use threads, or move to a shared mmap/file cache.
_model_cache: dict = {}  # Path → (mtime: float, artifact: dict)

# ── Historical analogues (k-NN on regime_training.csv) ───────────────────────
# Prebuilt once per process and reused. Stores the scaled feature matrix and
# matching outcome array so each per-ticker lookup is just a distance computation.
_analogues_index: dict | None = None   # {"X": ndarray, "wins": ndarray, "returns": ndarray, "cols": list}

_ANALOGUES_FEATURE_COLS = [
    "rsi", "adx", "hv20", "vix_close", "rel_strength_spy",
    "beta_60d", "atr_pct", "iv_rank_52w",
    "spy_rsi", "qqq_rsi", "iwm_rsi",
]
_ANALOGUES_K = 30  # neighbours to average


def _build_analogues_index() -> dict | None:
    """Load regime_training.csv once and build the scaled feature matrix."""
    csv_path = _ROOT / "data" / "regime_training.csv"
    if not csv_path.exists():
        return None
    try:
        from sklearn.preprocessing import StandardScaler
        df = pd.read_csv(csv_path)
        df2 = df.dropna(subset=["forward_return"]).copy()
        # Median-fill sparse features (beta_60d, iv_rank_52w) rather than dropping rows
        for col in _ANALOGUES_FEATURE_COLS:
            df2[col] = pd.to_numeric(df2[col], errors="coerce")
            df2[col] = df2[col].fillna(df2[col].median())
        usable = df2.dropna(subset=_ANALOGUES_FEATURE_COLS)
        if len(usable) < _ANALOGUES_K:
            return None
        X_raw = usable[_ANALOGUES_FEATURE_COLS].values.astype(float)
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(X_raw)
        wins = (usable["forward_return"].values > 0).astype(float)
        returns = usable["forward_return"].values.astype(float)
        medians = {c: float(usable[c].median()) for c in _ANALOGUES_FEATURE_COLS}
        return {"X": X_scaled, "wins": wins, "returns": returns,
                "scaler": scaler, "cols": _ANALOGUES_FEATURE_COLS, "medians": medians}
    except Exception:
        return None


def _get_analogues_index() -> dict | None:
    global _analogues_index
    if _analogues_index is None:
        _analogues_index = _build_analogues_index()
    return _analogues_index


def _compute_analogues(today_row: dict) -> dict:
    """
    Find k nearest historical rows to today_row and return win rate + avg return.
    Uses Euclidean distance on StandardScaler-normalised numeric features.
    Returns empty dict if index unavailable or today_row is missing features.
    """
    idx = _get_analogues_index()
    if idx is None:
        return {}
    try:
        medians = idx.get("medians", {})
        vals = [today_row.get(c) if today_row.get(c) is not None else medians.get(c, 0.0)
                for c in idx["cols"]]
        x = np.array(vals, dtype=float).reshape(1, -1)
        x_scaled = idx["scaler"].transform(x)
        dists = np.linalg.norm(idx["X"] - x_scaled, axis=1)
        k_idx = np.argpartition(dists, _ANALOGUES_K)[:_ANALOGUES_K]
        win_rate = float(np.mean(idx["wins"][k_idx]))
        avg_return = float(np.mean(idx["returns"][k_idx]))
        avg_dist = float(np.mean(dists[k_idx]))
        return {
            "analogues_win_rate":   round(win_rate, 3),
            "analogues_avg_return": round(avg_return, 4),
            "analogues_k":          _ANALOGUES_K,
            "analogues_avg_dist":   round(avg_dist, 3),
        }
    except Exception:
        return {}


def _load(path: Path) -> dict | None:
    if not path.exists():
        return None
    mtime = path.stat().st_mtime
    cached = _model_cache.get(path)
    if cached is not None and cached[0] == mtime:
        return cached[1]
    try:
        art = joblib.load(path)
        _model_cache[path] = (mtime, art)
        return art
    except Exception:
        return None


def _build_X(row: dict, artifact: dict) -> pd.DataFrame:
    """Convert a feature dict to a 1-row DataFrame the model expects."""
    encoders = artifact.get("feature_encoders") or {}
    # Derive numeric features from stored feature_cols, excluding categoricals
    feature_cols = artifact.get("feature_cols") or []
    numeric_cols = [c for c in feature_cols if c not in _CATEGORICAL_COLS]

    X = pd.DataFrame([{c: row.get(c) for c in numeric_cols}])
    for c in numeric_cols:
        X[c] = pd.to_numeric(X[c], errors="coerce")

    for col in _CATEGORICAL_COLS:
        if col not in feature_cols:
            continue
        val = str(row.get(col) or "unknown")
        enc = encoders.get(col)
        if enc is None:
            X[col] = 0
        else:
            known = set(enc.classes_)
            safe = val if val in known else enc.classes_[0]
            X[col] = enc.transform([safe])[0]

    # Column order must match training: numerics first, then categoricals in the order
    # they appear in feature_cols (which matches the training script's loop order).
    cat_cols_in_artifact = [c for c in feature_cols if c in _CATEGORICAL_COLS]
    return X[numeric_cols + cat_cols_in_artifact]


def _build_X_return(row: dict, artifact: dict) -> pd.DataFrame:
    """
    Build feature matrix for the return regressor (v2 artifact format).
    Uses dummy_cols (one-hot) instead of feature_encoders (LabelEncoder).
    Lag features are filled with NaN — XGBoost handles missing values natively,
    and for single-row live inference we don't have the prior N days per ticker.
    Feature schema is read from the artifact; falls back to the training module
    import only for artifacts saved before schema serialisation was added.
    """
    dummy_cols = artifact.get("dummy_cols") or []
    numeric_features = artifact.get("numeric_features")
    cat_cols         = artifact.get("cat_cols")
    lag_cols         = artifact.get("lag_cols")

    if numeric_features is None or cat_cols is None or lag_cols is None:
        from scripts.train_return_model import (
            NUMERIC_FEATURES as numeric_features,
            CAT_COLS as cat_cols,
            LAG_COLS as lag_cols,
        )

    X = pd.DataFrame(index=[0])
    for col in numeric_features:
        X[col] = pd.to_numeric(row.get(col), errors="coerce")

    # Lag features — unavailable for single-row inference; NaN is fine for XGBoost
    for col in lag_cols:
        X[col] = float("nan")

    # One-hot: build a tiny one-row dummies frame then align to dummy_cols
    cat_df = pd.DataFrame([{c: str(row.get(c, "unknown")) for c in cat_cols}])
    dummies = pd.get_dummies(cat_df, prefix_sep="__", drop_first=False)
    # Only add columns not already set above — prevents overwriting numeric/lag values
    for col in dummy_cols:
        if col not in X.columns:
            X[col] = dummies[col].values[0] if col in dummies.columns else 0

    return X[dummy_cols]


def _build_X_iv_direction(row: dict, artifact: dict) -> pd.DataFrame:
    """
    Build feature matrix for the IV direction classifier (v2 artifact format).
    Uses dummy_cols (one-hot get_dummies) instead of feature_encoders (LabelEncoder).
    artifact["dummy_cols"] = X_train.columns (numeric + one-hot); numeric cols are
    set first, one-hot cols added only for names not already in X.
    Feature schema is read from the artifact; falls back to the training module
    import only for artifacts saved before schema serialisation was added.
    """
    all_cols         = artifact.get("dummy_cols") or []
    numeric_features = artifact.get("numeric_features")
    cat_cols         = artifact.get("cat_cols")

    if numeric_features is None or cat_cols is None:
        from scripts.train_iv_direction_model import (
            NUMERIC_FEATURES as numeric_features,
            _CATEGORICAL_COLS as cat_cols,
        )

    X = pd.DataFrame(index=[0])
    for col in numeric_features:
        X[col] = pd.to_numeric(row.get(col), errors="coerce")

    cat_data = {col: str(row.get(col) or "unknown") for col in cat_cols}
    cat_df   = pd.DataFrame([cat_data])
    dummies  = pd.get_dummies(cat_df, prefix_sep="__", drop_first=False)
    # Only add columns not already set above — prevents overwriting numeric values
    for col in all_cols:
        if col not in X.columns:
            X[col] = dummies[col].values[0] if col in dummies.columns else 0

    return X[all_cols]


def _build_X_catboost(row: dict, artifact: dict) -> pd.DataFrame:
    """
    Feature matrix for CatBoost inference — numerics as float, categoricals as strings.
    Works for both regime_catboost and return_catboost artifacts (both store cat_cols + numeric_cols).
    """
    numeric_cols = artifact.get("numeric_cols") or []
    cat_cols     = artifact.get("cat_cols") or []
    lag_sources  = artifact.get("lag_sources") or []
    lag_days     = artifact.get("lag_days") or []

    X = pd.DataFrame(index=[0])
    for col in numeric_cols:
        X[col] = pd.to_numeric(row.get(col), errors="coerce")

    # Lag features — NaN for single-row inference (CatBoost handles missing values)
    for feat in lag_sources:
        for d in lag_days:
            X[f"{feat}_lag{d}"] = float("nan")
            X[f"{feat}_chg{d}"] = float("nan")

    for col in cat_cols:
        X[col] = str(row.get(col) or "unknown")

    all_cols = list(numeric_cols) + [f"{f}_lag{d}" for f in lag_sources for d in lag_days] + \
               [f"{f}_chg{d}" for f in lag_sources for d in lag_days] + list(cat_cols)
    # Only keep columns that exist in X (lag cols may not be present if lag_sources is empty)
    return X[[c for c in all_cols if c in X.columns]]


def predict_ticker(ticker: str, today_row: dict | None = None) -> dict:
    """
    Run all available trained models for one ticker.
    today_row: pre-built feature dict (avoids redundant yfinance fetch when
    called from predict_all with shared market context). If None, fetches live.
    Returns a structured dict with regime, expected_return, expected_vol, warnings.
    """
    warnings = []

    if today_row is None:
        try:
            from scripts.regime_backfill import _build_today_row, _fetch_market_context
            from scripts.data_fetch import get_vix_context, get_macro_context
            vix_close, spy_close, qqq_close, iwm_close = _fetch_market_context("6mo")
            vix_ctx   = get_vix_context()
            macro_ctx = get_macro_context(dte=10)
            today_row = _build_today_row(ticker, vix_close=vix_close, spy_close=spy_close,
                                         qqq_close=qqq_close, iwm_close=iwm_close,
                                         vix_ctx=vix_ctx, macro_ctx=macro_ctx)
        except Exception as e:
            warnings.append(f"Feature fetch failed: {e}")
            today_row = None

    if today_row is None:
        return {"ticker": ticker, "ok": False, "error": "Could not build feature row", "warnings": warnings}

    result: dict = {"ticker": ticker, "ok": True, "warnings": warnings,
                    "date": str(today_row.get("date", ""))}

    # ── Regime classifier (XGBoost + CatBoost averaged when both available) ──
    art = _load(_CLASSIFIER_CAL_PATH) or _load(_CLASSIFIER_PATH)
    if art is None:
        result["regime"] = None
        result["regime_proba"] = None
        warnings.append("Regime classifier not trained yet — run train_regime_classifier")
    else:
        try:
            X = _build_X(today_row, art)
            label_enc = art["label_encoder"]
            proba = art["model"].predict_proba(X)[0].astype(float)

            # Average with CatBoost when available
            cb_art = _load(_REGIME_CATBOOST_CAL_PATH) or _load(_REGIME_CATBOOST_PATH)
            if cb_art is not None:
                try:
                    X_cb = _build_X_catboost(today_row, cb_art)
                    cb_proba = cb_art["model"].predict_proba(X_cb)[0].astype(float)
                    # Both models trained with the same label_encoder so class order matches
                    proba = (proba + cb_proba) / 2.0
                    result["regime_model"] = "xgb+catboost"
                except Exception:
                    result["regime_model"] = "xgb"
            else:
                result["regime_model"] = "xgb"

            pred_idx = int(np.argmax(proba))
            result["regime"] = label_enc.classes_[pred_idx]
            result["regime_proba"] = {
                cls: round(float(p), 3)
                for cls, p in zip(label_enc.classes_, proba)
            }
        except Exception as e:
            result["regime"] = None
            result["regime_proba"] = None
            warnings.append(f"Regime classifier error: {e}")

    # ── Return regressor — config-gated ──────────────────────────────────────
    # Disabled by default (R²=-0.26). Auto-enables once the stored R² in the
    # artifact crosses `return_regressor_r2_threshold` in secrets.toml [ml],
    # or when `return_regressor_enabled = true` is set as a force override.
    _ml_cfg = _load_ml_config()
    art = _load(_RETURN_PATH)
    if art is None:
        result["expected_return"] = None
    else:
        stored_r2 = art.get("r2", -999.0)
        force_on  = _ml_cfg["return_regressor_enabled"]
        threshold = _ml_cfg["return_regressor_r2_threshold"]
        if force_on or stored_r2 >= threshold:
            try:
                # v2 artifacts use dummy_cols (one-hot); v1 used feature_encoders
                if "dummy_cols" in art:
                    X = _build_X_return(today_row, art)
                else:
                    X = _build_X(today_row, art)
                xgb_ret = float(art["model"].predict(X)[0])

                # Average with CatBoost return model when available and also above threshold
                cb_ret_art = _load(_RETURN_CATBOOST_PATH)
                if cb_ret_art is not None:
                    cb_r2 = cb_ret_art.get("r2", -999.0)
                    if force_on or cb_r2 >= threshold:
                        try:
                            X_cb = _build_X_catboost(today_row, cb_ret_art)
                            cb_ret = float(cb_ret_art["model"].predict(X_cb)[0])
                            xgb_ret = (xgb_ret + cb_ret) / 2.0
                        except Exception:
                            pass

                result["expected_return"] = round(xgb_ret, 4)
            except Exception as e:
                result["expected_return"] = None
                warnings.append(f"Return model error: {e}")
        else:
            result["expected_return"] = None
            warnings.append(
                f"Return regressor inactive (R²={stored_r2:.3f} < threshold {threshold})"
            )

    # ── Volatility regressor ─────────────────────────────────────────────────
    art = _load(_VOLATILITY_PATH)
    if art is None:
        result["expected_vol"] = None
        warnings.append("Volatility model not trained yet — run train_volatility_model")
    else:
        try:
            X = _build_X(today_row, art)
            result["expected_vol"] = round(float(art["model"].predict(X)[0]), 4)
        except Exception as e:
            result["expected_vol"] = None
            warnings.append(f"Volatility model error: {e}")

    # ── Expected move (derived from vol, not a separate model) ──────────────
    # Formula: annualized_vol × √(10/252) → 10-trading-day 1-σ move as a fraction.
    # This is the standard options market expected move approximation.
    ev = result.get("expected_vol")
    result["expected_move_pct"] = round(ev * math.sqrt(10 / 252), 4) if ev is not None else None

    # ── Direction classifier ──────────────────────────────────────────────────
    art = _load(_DIRECTION_CAL_PATH) or _load(_DIRECTION_PATH)
    if art is None:
        result["p_up"] = None
        result["direction"] = None
        warnings.append("Direction model not trained yet — run train_direction_model")
    else:
        try:
            X = _build_X(today_row, art)
            p_up = float(art["model"].predict_proba(X)[0][1])
            result["p_up"]      = round(p_up, 4)
            result["direction"] = "Up" if p_up >= 0.5 else "Down"
        except Exception as e:
            result["p_up"] = None
            result["direction"] = None
            warnings.append(f"Direction model error: {e}")

    # ── IV Direction classifier ───────────────────────────────────────────────
    art = _load(_IV_DIRECTION_CAL_PATH) or _load(_IV_DIRECTION_PATH)
    if art is None:
        result["iv_expanding_prob"] = None
        result["iv_direction"] = None
        warnings.append("IV Direction model not trained yet — run train_iv_direction_model")
    else:
        try:
            if "dummy_cols" in art:
                X = _build_X_iv_direction(today_row, art)
            else:
                X = _build_X(today_row, art)
            p_exp = float(art["model"].predict_proba(X)[0][1])
            result["iv_expanding_prob"] = round(p_exp, 4)
            result["iv_direction"] = _LABEL_IV_EXP if p_exp >= 0.5 else _LABEL_IV_CON
        except Exception as e:
            result["iv_expanding_prob"] = None
            result["iv_direction"] = None
            warnings.append(f"IV Direction model error: {e}")

    # ── GARCH conditional vol forecast ───────────────────────────────────────
    try:
        from scripts.train_garch_model import get_garch_forecast as _garch_fc
        _garch_val = _garch_fc(ticker)
        result["garch_vol_forecast"] = round(_garch_val, 4) if _garch_val is not None else None
    except Exception:
        result["garch_vol_forecast"] = None

    # ── Meta-ensemble scorer ─────────────────────────────────────────────────
    art = _load(_META_CAL_PATH) or _load(_META_PATH)
    if art is None:
        result["meta_score"] = None
        warnings.append("Meta-ensemble not trained yet — run train_meta_ensemble")
    else:
        try:
            # Build meta-input from the other models' outputs.
            # Must include all features in art["meta_features"] (7 base + 2 derived).
            regime_proba = result.get("regime_proba") or {}
            _p_up_t  = regime_proba.get(_LABEL_UPTREND,    1 / 3)
            _p_down  = regime_proba.get(_LABEL_DOWNTREND,  1 / 3)
            _p_range = regime_proba.get(_LABEL_RANGEBOUND, 1 / 3)
            _p_up    = result.get("p_up") or 0.5
            _p_iv    = result.get("iv_expanding_prob") or 0.5

            # regime_entropy: uncertainty across regime distribution (0=certain, ~1.1=max)
            _eps = 1e-9
            _regime_entropy = -sum(
                p * math.log(p + _eps) for p in [_p_up_t, _p_down, _p_range]
            )
            # pred_std: directional disagreement across three probability signals
            _pred_std = float(np.std([_p_up_t, _p_up, _p_iv]))

            meta_row = {
                "p_uptrend":         _p_up_t,
                "p_downtrend":       _p_down,
                "p_rangebound":      _p_range,
                "expected_return":   result.get("expected_return") or 0.0,
                "expected_vol":      result.get("expected_vol") or 0.25,
                "p_up":              _p_up,
                "iv_expanding_prob": _p_iv,
                "regime_entropy":    round(_regime_entropy, 4),
                "pred_std":          round(_pred_std, 4),
            }
            X_meta = pd.DataFrame([meta_row])[art["meta_features"]]
            p_meta = float(art["model"].predict_proba(X_meta)[0][1])
            result["meta_score"] = round(p_meta * 100, 1)   # 0–100
        except Exception as e:
            result["meta_score"] = None
            warnings.append(f"Meta-ensemble error: {e}")

    # ── POP classifier (trained on paper trade outcomes) ────────────────────
    art = _load(_POP_CAL_PATH) or _load(_POP_PATH)
    if art is None:
        result["pop_score"] = None
        warnings.append("POP model not trained yet — run train_pop_model")
    else:
        try:
            from scripts.train_pop_model import build_feature_matrix as _pop_features
            X_pop, _ = _pop_features(pd.DataFrame([today_row]), encoders=art.get("feature_encoders"), fit=False)
            result["pop_score"] = round(float(art["model"].predict_proba(X_pop)[0][1]), 4)
        except Exception as e:
            result["pop_score"] = None
            warnings.append(f"POP model error: {e}")

    # ── Historical analogues (k-NN on regime_training.csv) ──────────────────
    analogues = _compute_analogues(today_row)
    result.update(analogues)

    # ── Anomaly detector ─────────────────────────────────────────────────────
    art = _load(_ANOMALY_PATH)
    if art is None:
        result["anomaly_score"] = None
        result["is_anomaly"]    = None
        result["anomaly_flags"] = []
        warnings.append("Anomaly detector not trained yet — run train_anomaly_detector")
    else:
        try:
            from scripts.train_anomaly_detector import score_row as _score_anomaly
            anom = _score_anomaly(today_row, art)
            result.update(anom)
        except Exception as e:
            result["anomaly_score"] = None
            result["is_anomaly"]    = None
            result["anomaly_flags"] = []
            warnings.append(f"Anomaly detector error: {e}")

    # ── Prediction distribution: model-agreement ensemble ────────────────────
    # Aggregate every directional probability signal into a single distribution
    # object. This lets callers distinguish "65 with high agreement across 5
    # models" from "65 with wide disagreement" — which look identical on a
    # plain meta_score but carry very different trading implications.
    _signals: dict[str, float] = {}
    if result.get("meta_score") is not None:
        _signals["meta"] = result["meta_score"] / 100.0
    if result.get("p_up") is not None:
        _signals["p_up"] = float(result["p_up"])
    if result.get("pop_score") is not None:
        _signals["pop"] = float(result["pop_score"])
    if result.get("analogues_win_rate") is not None and (result.get("analogues_k") or 0) >= 10:
        _signals["analogues"] = float(result["analogues_win_rate"])
    _rp = result.get("regime_proba") or {}
    if _rp.get("Uptrend") is not None:
        _signals["regime_up"] = float(_rp["Uptrend"])

    if _signals:
        _vals = list(_signals.values())
        _p_win = float(np.mean(_vals))
        _ev_std = float(np.std(_vals))
        # confidence ∈ [0,1]: 0 std → 1.0 (perfect agreement), 0.5 std → 0.0
        _confidence = max(0.0, round(1.0 - 2.0 * _ev_std, 3))
        _agreement = "High" if _confidence >= 0.70 else "Medium" if _confidence >= 0.40 else "Low"
        result["pred_dist"] = {
            "p_win":           round(_p_win, 3),
            "ev_std":          round(_ev_std, 3),
            "confidence":      _confidence,
            "model_agreement": _agreement,
            "n_signals":       len(_signals),
            "signals":         {k: round(v, 3) for k, v in _signals.items()},
            # Filled in by build_top_trades once Monte Carlo has run per-candidate
            "p10_pnl":         None,
            "p90_pnl":         None,
            "ev_per_share":    None,
            "vol_source":      None,
        }
    else:
        result["pred_dist"] = None

    result["live"] = _build_live_context(today_row)

    # Record today's regime and compute consecutive-day streak.
    # Used by candidate_ranker's ML regime override gate — override only fires
    # when the regime has persisted for >= N days, preventing single-day noise.
    try:
        from scripts.regime_history import regime_history as _rh
        from datetime import date as _date
        _streak = _rh.record_and_streak(
            ticker=ticker,
            date_str=_date.today().isoformat(),
            regime=result.get("regime"),
            regime_proba=result.get("regime_proba"),
            pred_dist=result.get("pred_dist"),
        )
        result["ml_regime_streak"] = _streak
    except Exception as _rh_err:
        log.debug(f"[regime_history] streak tracking skipped: {_rh_err}")
        result["ml_regime_streak"] = 0

    return result


# Keys extracted from the feature row for display (not model inputs).
_LIVE_CONTEXT_KEYS = (
    "close", "rsi", "hv20", "garch_conditional_var", "trend",
    "vix_close", "beta_60d", "atr_pct", "iv_rank_52w",
    "vol_oi_ratio", "iv_skew", "iv_term_slope", "otm_pcr",
    "spy_trend", "qqq_trend", "iwm_trend",
    "sector_etf", "sector_trend", "sector_rsi", "sector_iv_ratio",
    "vvix", "vix_3m", "vix_term_slope",
    "earnings_inside_expiry", "news_sentiment_score",
    "analyst_rec_change", "short_interest_pct",
    "iv_skew_20d", "gex_proxy", "max_pain_strike", "oi_concentration", "wings_iv_ratio",
    "yield_10y", "yield_3m", "yield_curve", "dollar_index",
    "fed_within_dte", "cpi_within_dte",
)


def _build_live_context(row: dict) -> dict:
    ctx = {k: row.get(k) for k in _LIVE_CONTEXT_KEYS}
    # rel_strength_spy stored under a different key in the feature row
    ctx["rel_strength"] = row.get("rel_strength_spy")
    return ctx


def predict_all(tickers: list[str] | None = None) -> dict:
    """
    Run predictions for all tickers, fetching shared market context once.
    Returns {ok, predictions: [...], warnings: [...], model_status: {...}}
    """
    from config.watchlist import WATCHLIST
    from scripts.regime_backfill import _build_today_row, _fetch_market_context
    from scripts.data_fetch import get_vix_context, get_macro_context

    if tickers is None:
        tickers = list(WATCHLIST.keys()) if isinstance(WATCHLIST, dict) else list(WATCHLIST)

    top_warnings = []
    try:
        vix_close, spy_close, qqq_close, iwm_close = _fetch_market_context("6mo")
    except Exception as e:
        top_warnings.append(f"Market context fetch failed: {e}")
        vix_close = spy_close = qqq_close = iwm_close = None

    try:
        vix_ctx = get_vix_context()
    except Exception:
        vix_ctx = {}
    try:
        macro_ctx = get_macro_context(dte=10)
    except Exception:
        macro_ctx = {}

    predictions = []
    for ticker in tickers:
        try:
            today_row = _build_today_row(
                ticker,
                vix_close=vix_close, spy_close=spy_close,
                qqq_close=qqq_close, iwm_close=iwm_close,
                vix_ctx=vix_ctx, macro_ctx=macro_ctx,
            )
        except Exception as e:
            predictions.append({"ticker": ticker, "ok": False, "error": str(e), "warnings": []})
            continue
        pred = predict_ticker(ticker, today_row=today_row)
        predictions.append(pred)

    model_status = {
        "regime_classifier":       _CLASSIFIER_PATH.exists(),
        "return_regressor":        _RETURN_PATH.exists(),
        "volatility_regressor":    _VOLATILITY_PATH.exists(),
        "direction_classifier":    _DIRECTION_PATH.exists(),
        "iv_direction_classifier": _IV_DIRECTION_PATH.exists(),
        "meta_ensemble":           _META_PATH.exists(),
        "anomaly_detector":        _ANOMALY_PATH.exists(),
    }
    return {
        "ok": True,
        "predictions": predictions,
        "model_status": model_status,
        "warnings": top_warnings,
    }


if __name__ == "__main__":
    tickers = sys.argv[1:] or None
    result = predict_all(tickers)
    for p in result["predictions"]:
        w = "; ".join(p.get("warnings") or [])
        regime = p.get("regime") or "—"
        ret    = p.get("expected_return")
        vol    = p.get("expected_vol")
        p_up   = p.get("p_up")
        iv_dir      = p.get("iv_direction") or "—"
        iv_prob     = p.get("iv_expanding_prob")
        meta_score  = p.get("meta_score")
        anom_score  = p.get("anomaly_score")
        is_anomaly  = p.get("is_anomaly")
        if ret is not None and vol is not None and p_up is not None:
            iv_str   = f"  IV={iv_dir}({iv_prob:.0%})" if iv_prob is not None else ""
            meta_str = f"  meta={meta_score:.0f}/100" if meta_score is not None else ""
            anom_str = (f"  anom={anom_score:.0f}{'⚠' if is_anomaly else ''}"
                        if anom_score is not None else "")
            print(f"{p['ticker']:6s}  regime={regime:12s}  "
                  f"ret={ret:+.2%}  vol={vol:.2%}  P(up)={p_up:.0%}"
                  f"{iv_str}{meta_str}{anom_str}")
        else:
            print(f"{p['ticker']:6s}  {p.get('error') or w}")
    if result.get("warnings"):
        for w in result["warnings"]:
            print(f"[WARN] {w}")
